version: '3'
services: 
    parent:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        networks:
            - development
networks:
    development:
        name: 'development'
        driver: bridge